### ISSUE TITLE
python 3.7 support

### ISSUE THREAD

**Issue by aviskase** [mozilla/PyPOM#126]
Currently, there is confirmed support only for python 2.7 and 3.6.
What about python 3.7 ?

**Comment by davehunt** [comment]
@aviskase please feel free to submit a pull request. I'm not sure this project is actively maintained these days. Perhaps @davidemoro can correct me, but I no longer have much time to work on it.

**Comment by davidemoro** [comment]
Hi @davehunt, @aviskase,

ouch, I thought there were other Mozilla maintainers! I am overworking in
this period but I can fix the python 3.7 compatibility. Just give me a
couple of weeks for the PR.

**Comment by davehunt** [comment]
@davidemoro there are still Mozilla consumers, so I would expect any breakages to be addressed, but I'm not sure there is any feature development at this time.

@aviskase have you seenn issues running against Python 3.7? It may not be explicitly supported, but that doesn't mean that it wouldn't work.

**Comment by aviskase** [comment]
@davehunt ran it, seems to be ok (but we've just started using PyPom)

**Comment by davidemoro** [comment]
All tests passing with py37 without any code change. cc @aviskase @davehunt 

I think with issue can be closed

**Comment by adriangonciarz** [comment]
Works solid with 3.7
