### ISSUE TITLE
sing strategy as xpath is not working with region

### ISSUE THREAD

**Issue by anurag-gethullo** [mozilla/PyPOM#85]
First of all thanks for the great library to share, but I am facing the minor issue by using XPATH locator within Region.
When  using XPATH locator in the Region class, over there its giving me the first element found with that XPATH throughout the page, instead it should provide me the element found with that XPATH specific to that Region.
here is what I tried
**result.html**
```
<ol>
    <li class="result">
        <span class="name">Result 1</span>
        <a href="./detail/1/">detail</a>
    </li>
    <li class="result">
        <span class="name">Result 2</span>
        <a href="./detail/2/">detail</a>
    </li>
    <li class="result">
        <span class="name">Result 3</span>
        <a href="./detail/3/">detail</a>
    </li>
    <li class="result">
        <span class="name">Result 4</span>
        <a href="./detail/4/">detail</a>
    </li>
</ol>
```

**results_page.py**
```
class Results(Page):
    _result_locator = (By.CLASS_NAME, 'result')

    @property
    def results(self):
        return [self.Result(self, el) for el in self.find_elements(*self._result_locator)]

    class Result(Region):
        _name_locator = **(By.XPATH, '//span')**
        _detail_locator = **(By.TAG_NAME, '//a')**

        @property
        def name(self):
            return self.find_element(*self._name_locator).text

        @property
        def detail_link(self):
            return self.find_element(*self._detail_locator).get_property("href")
```

**main.py**
```
result_page = Results(browser, base_url).open()

for el in (result_page.results):
    print el.name
```

**The final output:
Result 1
Result 1
Result 1
Result 1**

I tried to run the example you have shared in documentation that works great, but that is with CLASS_NAME and TAG_NAME.

**Comment by anurag-gethullo** [comment]
Sorry It was my mistake
I was providing the XPATH as `//span` instead it should have been './span'

**Comment by davehunt** [comment]
Thank you for using this library, I'm glad you find it useful. If you think the documentation would benefit from an XPath example for locating elements within regions then please feel free to open a pull request. 😊
